// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcp9GXSU_KcUopPk4jrNuG4y_jJcUOhJg',
    appId: '1:457959018224:web:40a87501936a18efb77c35',
    messagingSenderId: '457959018224',
    projectId: 'overlord-5076b',
    authDomain: 'overlord-5076b.firebaseapp.com',
    storageBucket: 'overlord-5076b.firebasestorage.app',
    measurementId: 'G-S725JPVCQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgCE0rZoPBqW9PoQjhB8iIWxD2hhYB2q8',
    appId: '1:457959018224:android:c6dda81d77b163e1b77c35',
    messagingSenderId: '457959018224',
    projectId: 'overlord-5076b',
    storageBucket: 'overlord-5076b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-tjqnPmCTPxaY3hhnfYR1Z4zpoY67A4',
    appId: '1:457959018224:ios:1bb487eec4a97c8cb77c35',
    messagingSenderId: '457959018224',
    projectId: 'overlord-5076b',
    storageBucket: 'overlord-5076b.firebasestorage.app',
    iosBundleId: 'com.example.hivemindApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-tjqnPmCTPxaY3hhnfYR1Z4zpoY67A4',
    appId: '1:457959018224:ios:1bb487eec4a97c8cb77c35',
    messagingSenderId: '457959018224',
    projectId: 'overlord-5076b',
    storageBucket: 'overlord-5076b.firebasestorage.app',
    iosBundleId: 'com.example.hivemindApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcp9GXSU_KcUopPk4jrNuG4y_jJcUOhJg',
    appId: '1:457959018224:web:54b83e2842e1096db77c35',
    messagingSenderId: '457959018224',
    projectId: 'overlord-5076b',
    authDomain: 'overlord-5076b.firebaseapp.com',
    storageBucket: 'overlord-5076b.firebasestorage.app',
    measurementId: 'G-87TP81DKNV',
  );

}